#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \Tsc\CatStorageSystem\Commands\RenameFileCommand());
$application->add(new \Tsc\CatStorageSystem\Commands\ListFileCommand());

try {
    $application->run();
} catch (Exception $e) {
    echo $e->getMessage() . PHP_EOL;
}